// <auto-generated />
using System;
using APBD_Test2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APBDTest2.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250610084426_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APBD_Test2.Models.Author", b =>
                {
                    b.Property<int>("IdAuthor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAuthor"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdAuthor");

                    b.ToTable("Author", (string)null);

                    b.HasData(
                        new
                        {
                            IdAuthor = 1,
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            IdAuthor = 2,
                            FirstName = "Jane",
                            LastName = "Smith"
                        },
                        new
                        {
                            IdAuthor = 3,
                            FirstName = "Alice",
                            LastName = "Johnson"
                        });
                });

            modelBuilder.Entity("APBD_Test2.Models.Book", b =>
                {
                    b.Property<int>("IdBook")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBook"));

                    b.Property<int>("IdPublishingHouse")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdBook");

                    b.HasIndex("IdPublishingHouse");

                    b.ToTable("Book", (string)null);

                    b.HasData(
                        new
                        {
                            IdBook = 1,
                            IdPublishingHouse = 1,
                            Name = "Book One",
                            ReleaseDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdBook = 2,
                            IdPublishingHouse = 2,
                            Name = "Book Two",
                            ReleaseDate = new DateTime(2021, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdBook = 3,
                            IdPublishingHouse = 3,
                            Name = "Book Three",
                            ReleaseDate = new DateTime(2022, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("APBD_Test2.Models.BookAuthor", b =>
                {
                    b.Property<int>("IdBook")
                        .HasColumnType("int");

                    b.Property<int>("IdAuthor")
                        .HasColumnType("int");

                    b.HasKey("IdBook", "IdAuthor");

                    b.HasIndex("IdAuthor");

                    b.ToTable("BookAuthors");

                    b.HasData(
                        new
                        {
                            IdBook = 1,
                            IdAuthor = 1
                        },
                        new
                        {
                            IdBook = 2,
                            IdAuthor = 2
                        },
                        new
                        {
                            IdBook = 3,
                            IdAuthor = 3
                        });
                });

            modelBuilder.Entity("APBD_Test2.Models.BookGenre", b =>
                {
                    b.Property<int>("IdGenre")
                        .HasColumnType("int");

                    b.Property<int>("IdBook")
                        .HasColumnType("int");

                    b.HasKey("IdGenre", "IdBook");

                    b.HasIndex("IdBook");

                    b.ToTable("BookGenres");

                    b.HasData(
                        new
                        {
                            IdGenre = 1,
                            IdBook = 1
                        },
                        new
                        {
                            IdGenre = 2,
                            IdBook = 2
                        },
                        new
                        {
                            IdGenre = 3,
                            IdBook = 3
                        });
                });

            modelBuilder.Entity("APBD_Test2.Models.Genre", b =>
                {
                    b.Property<int>("IdGenre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGenre"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdGenre");

                    b.ToTable("Genre", (string)null);

                    b.HasData(
                        new
                        {
                            IdGenre = 1,
                            Name = "Fiction"
                        },
                        new
                        {
                            IdGenre = 2,
                            Name = "Non-Fiction"
                        },
                        new
                        {
                            IdGenre = 3,
                            Name = "Science Fiction"
                        });
                });

            modelBuilder.Entity("APBD_Test2.Models.PublishingHouse", b =>
                {
                    b.Property<int>("IdPublishingHouse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPublishingHouse"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdPublishingHouse");

                    b.ToTable("PublishingHouse", (string)null);

                    b.HasData(
                        new
                        {
                            IdPublishingHouse = 1,
                            City = "New York",
                            Country = "USA",
                            Name = "Publisher One"
                        },
                        new
                        {
                            IdPublishingHouse = 2,
                            City = "London",
                            Country = "UK",
                            Name = "Publisher Two"
                        },
                        new
                        {
                            IdPublishingHouse = 3,
                            City = "Toronto",
                            Country = "Canada",
                            Name = "Publisher Three"
                        });
                });

            modelBuilder.Entity("APBD_Test2.Models.Book", b =>
                {
                    b.HasOne("APBD_Test2.Models.PublishingHouse", "PublishingHouse")
                        .WithMany("Books")
                        .HasForeignKey("IdPublishingHouse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PublishingHouse");
                });

            modelBuilder.Entity("APBD_Test2.Models.BookAuthor", b =>
                {
                    b.HasOne("APBD_Test2.Models.Author", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("IdAuthor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_Test2.Models.Book", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("IdBook")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("APBD_Test2.Models.BookGenre", b =>
                {
                    b.HasOne("APBD_Test2.Models.Book", "Book")
                        .WithMany("BookGenres")
                        .HasForeignKey("IdBook")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_Test2.Models.Genre", "Genre")
                        .WithMany("BookGenres")
                        .HasForeignKey("IdGenre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("APBD_Test2.Models.Author", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("APBD_Test2.Models.Book", b =>
                {
                    b.Navigation("BookAuthors");

                    b.Navigation("BookGenres");
                });

            modelBuilder.Entity("APBD_Test2.Models.Genre", b =>
                {
                    b.Navigation("BookGenres");
                });

            modelBuilder.Entity("APBD_Test2.Models.PublishingHouse", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
